<div class="product-container cc-results ">

 <?php  foreach ($products as $key => $value) { ?>
    <?php if($key <= 0){ ?>
    <div class="row cc-result">
        <!-- <div class="highest-featured">
            Highest Cashback on dining!
        </div> -->
        <div class="col-md-5 col-sm-5 col-xs-9">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 rRow">                                                    
                    <p class="card-name"><?php echo $value['companyName'].' '. $value['productName']; ?></p>
                    <div class="row">
                        <div class="col-md-5 col-sm-5 col-xs-5 cc-cards">
                            <img class="img-responsive" src="<?php echo $value['logo']; ?>" alt="<?php echo $value['companyName'].' '. $value['productName']; ?>"/>
                            <ul class="list-unstyled lightgrey">
                                <li><img src="<?php echo $this->url->get('assets/img/cc-card1.png');?>" alt=""/> <span>Octupus Card</span></li>
                                <li><img src="<?php echo $this->url->get('assets/img/cc-card2.png');?>" alt=""/> <span>valid TaoBao</span></li>
                            </ul>
                        </div>
                        <div class="col-md-7 col-sm-7 col-xs-7 card-details lightgrey">
                            <strong class="concat_char"><?php echo $lang->_("common_23"); ?></strong>
                            <ul class="list-unstyled">
                                <?php foreach ($value['keyBenefits'] as $keybenefits) { ?>
                                    <li><i class="fa fa-check fa-lg"></i><span><?php echo $keybenefits; ?></span></li>
                                <?php } ?>
                            </ul>
                            <?php if(!empty($value['rewards']['rewardsBeware'])){ ?>
                                <strong class="concat_char"><?php echo $lang->_("common_22"); ?></strong>
                                <ul class="list-unstyled">
                                    <li><i class="fa fa-minus fa-lg"></i><span><?php echo $value['rewards']['rewardsBeware']; ?></span></li>
                                </ul>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
            <!-- <div class="label label-promo lightgrey row">
                <div class="col-md-1 col-sm-1 col-xs-1 padding-0">
                    <img src="<?php echo $this->url->get('assets/img/promo.png');?>" />
                </div>
                <div class="col-md-10 col-sm-10 col-xs-10 padding-0 center-text concat_char" style="margin-top: 2px;">
                    <span>Promo: some promo text here</span>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1 padding-0" style="font-size: 20px;">
                    <i class="fa fa-info-circle"></i>
                </div>
            </div> -->
        </div>

        <div class="col-md-5 col-sm-5 hidden-xs">
            <div class="row">
                <div class="col-md-3 col-sm-3 rRow padding-0-5">
                    <p>Up to <em>5.00%</em></p>
                    <p><a href="" class="more"><i class="fa fa-question-circle"></i><?php echo $lang->_("common_21"); ?></a></p>
                </div>
                <div class="col-md-3 col-sm-3 rRow padding-0-5">
                    <p>1 mile =<br/><em>$6</em></p>
                    <p><a href="" class="more"><i class="fa fa-question-circle"></i><?php echo $lang->_("common_21"); ?></a></p>
                </div>
                <div class="col-md-3 col-sm-3 rRow padding-0-5">
                    <p>Up to<br/><em>3x</em></p>
                    <p><a href="" class="more"><i class="fa fa-question-circle"></i><?php echo $lang->_("common_21"); ?></a></p>
                </div>
                <div class="col-md-3 col-sm-3 rRow padding-0-5">
                    <p><em>$0</em <br/>waived for first year*</p>
                    <p><a href="" class="more"><i class="fa fa-question-circle"></i><?php echo $lang->_("common_21"); ?></a></p>
                </div>
            </div>
        </div>

        <div class="col-md-2 col-sm-2 col-xs-3">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 callus">
                    <button type="button" class="btn btn-warning btn-go" data-toggle="modal" data-target="#cc-modal"><?php echo $lang->_("common_24"); ?> <i class="hidden-xs fa fa-chevron-right"></i></button>

                    <span class="lightgrey" style="font-size: 12px;"><?php echo $lang->_("common_20"); ?></span>
                    <span class="call-num"><?php echo $this->config->project->phone; ?></span>
                    <span class="get-card"><a href=""><i class="fa fa-question-circle"></i><?php echo $lang->_("common_19", array('vartical' => 'Cards')); ?></a></span>
                    <span class="compare lightgrey"><input type="checkbox"><?php echo $lang->_("common_18"); ?></span>
                </div>
            </div>
        </div>
    </div>
    <?php } ?>
    <?php } ?>


<hr class="green">
<div class="row">
    <div class="col-lg-4 "><p class="feature-title1">Promos</p></div>
    <div class="col-lg-8 feature-title2">Local Retail Transactions HK$3 =1 Mile Promotion</div>
</div>
<div class="row">
    <div class="col-lg-4 text-center rRow">
        <img src="<?php echo $this->url->get('/assets/img/icons/promo.png');?>" alt=""/>
        <p style="font-weight: bold;">Prpomo Details</p>
    </div>
    <div class="col-lg-8 lightgrey">
        <p>One must choose to participate in the DBS$ Redemption Scheme, activate the New Card within 2 months of the New
            Card issuance date, and conduct Eligible Transactions in an accumulated amount of HK$3,000 or above with the New
            Card during the Spending Period the amount of all accumulated Local Retail Transactions therein will be entitled to
            the mile conversion rate HK$3 = 1 mile offer;</p>
        <p>For New Customer, only the first HK$10,000 Local Retail Transactions conducted by the New Card within the Spending
            Period will be eligible to the Extra Reward.</p>
        <p>For Existing Customer, only the first HK$5,000 Local Retail Transactions conducted by the New Card within the
            Spending Period will be eligible to the Extra Reward.</p>
    </div>
</div>

<div class="benefits">
    <hr class="blue">
    <div class="row">
        <div class="col-lg-12"><p class="feature-title1">Benefits</p></div>
    </div>
    <div class="row bRow">
        <div class="col-lg-4 text-center rRow">
            <img src="<?php echo $this->url->get('/assets/img/icons/reward.png');?>" alt=""/>
            <p style="font-weight: bold;">Rewards</p>
        </div>
        <div class="col-lg-8 lightgrey">
            <ul class="key-val">
                <li class="clearfix"><label>Conversion rate</label> <p>P50 spent = 1 reward point (points expire after 1 year)</p></li>
                <li class="clearfix"><label>Multiplier</label> <p>x2 when shopping at Ayala malls</p></li>
                <li class="clearfix"><label>Spent on Dining</label> <p><i class="fa fa-check fa-lg"></i>A Pint at Draft (300 points), a Whopper (250 points)</p></li>
                <li class="clearfix"><label>Spent on Dining</label> <p><i class="fa fa-times fa-lg"></i>A Pint at Draft (300 points), a Whopper (250 points)</p></li>
            </ul>
        </div>
    </div>
    <div class="row bRow" style="padding: 20px 0 20px 0;">
        <div class="col-lg-4 text-center lightgrey">
            <img src="<?php echo $this->url->get('/assets/img/cashback-inactive.png');?>" alt=""/>
            <p style="font-weight: bold;">Cashback</p>
        </div>
        <div class="col-lg-8 lightgrey">
            <p style="font-size: 1.5em;">No Cashback</p>
        </div>
    </div>
    <div class="row bRow" style="padding: 20px 0 20px 0;">
        <div class="col-lg-4 text-center lightgrey">
            <img src="<?php echo $this->url->get('/assets/img/travel-inactive.png');?>" alt=""/>
            <p style="font-weight: bold;">Cashback</p>
        </div>
        <div class="col-lg-8 lightgrey">
            <p style="font-size: 1.5em;">No Travel</p>
        </div>
    </div>
    <div class="row bRow" style="padding: 20px 0 20px 0;">
        <div class="col-lg-4 text-center lightgrey">
            <img src="<?php echo $this->url->get('/assets/img/discounts-inactive.png');?>" alt=""/>
            <p style="font-weight: bold;">Cashback</p>
        </div>
        <div class="col-lg-8 lightgrey">
            <p style="font-size: 1.5em;">No Discounts</p>
        </div>
    </div>
</div>


<div class="bal-trans">
    <hr class="blue">
    <div class="row">
        <div class="col-lg-12"><p class="feature-title1">Fees, Rate and Balance Transfer</p></div>
    </div>
    <div class="row bRow">
        <div class="col-lg-3 text-center rRow">
            <img src="<?php echo $this->url->get('/assets/img/icons/balance-transfer.png');?>" alt=""/>
            <p style="font-weight: bold;">Balance Transfer</p>
        </div>
        <div class="col-lg-9 lightgrey">
            <ul class="key-val">
                <li class="clearfix"><label>1 month</label> <p>2.00%</p></li>
                <li class="clearfix"><label>3 months</label> <p>1.20% (Total Balance transfer amount needs to be at least P20,000)</p></li>
                <li class="clearfix"><label>6 months</label> <p>7.00%</p></li>
                <li class="clearfix"><label>12 months</label> <p>-</p></li>
                <li class="clearfix"><label>18 months</label> <p>0.55% (Total Balance transfer amount can be at most P30,000)</p></li>
                <li class="clearfix"><label>24 months</label> <p>1.00%</p></li>
                <li class="clearfix"><label>30 months</label> <p>-</p></li>
                <li class="clearfix"><label>Bal. Transfer Amount</label> <p>P1,000</p></li>
                <li class="clearfix"><label>Min. Amount Monthly</label> <p>P500</p></li>
                <li class="clearfix"><label>Pre-Termination Fee</label> <p>P300 or 3% of the outstanding amount (whichever is higher)</p></li>
                <li class="clearfix"><label>Other Conditions:</label> <p>-</p></li>
            </ul>
        </div>
    </div>
    <div class="row bRow">
        <div class="col-lg-3 text-center rRow">
            <img src="<?php echo $this->url->get('/assets/img/icons/interest.png');?>" alt=""/>
            <p style="font-weight: bold;">Interest and APR</p>
        </div>
        <div class="col-lg-9 lightgrey">
            <ul class="key-val">
                <li class="clearfix"><label>Purchase Interest</label> <p>2.00%</p></li>
                <li class="clearfix"><label>Purchase APR</label> <p>30.00%</p></li>
                <li class="clearfix"><label>Cash Advance Interest</label> <p>5.5%</p></li>
                <li class="clearfix"><label>Cash Advance APR</label> <p>35.45%</p></li>
                <li class="clearfix"><label>Interest Free Period</label> <p>51 days</p></li>
            </ul>
        </div>
    </div>
    <div class="row bRow">
        <div class="col-lg-3 text-center rRow">
            <img src="<?php echo $this->url->get('/assets/img/icons/payment-charges.png');?>" alt=""/>
            <p style="font-weight: bold;">Payment Charges</p>
        </div>
        <div class="col-lg-9 lightgrey">
            <ul class="key-val">
                <li class="clearfix"><label>Minimum Payment</label> <p>3% of total outstanding balance or P500 (whichever is higher)</p></li>
                <li class="clearfix"><label>Late Payment</label> <p>5% of total outstanding balance</p></li>
            </ul>
        </div>
    </div>
    <div class="row bRow">
        <div class="col-lg-3 text-center rRow">
            <img src="<?php echo $this->url->get('/assets/img/icons/fees.png');?>" alt=""/>
            <p style="font-weight: bold;">Fees</p>
        </div>
        <div class="col-lg-9 lightgrey">
            <ul class="key-val">
                <li class="clearfix"><label>Annual Fee</label> <p>P2,000 (First Year waived)</p></li>
                <li class="clearfix"><label>Foreign Transaction</label> <p>3%</p></li>
                <li class="clearfix"><label>Credit Over Limit</label> <p>P500</p></li>
                <li class="clearfix"><label>Supplementary Card</label> <p>P1,000 per year (the first two are free for life)</p></li>
                <li class="clearfix"><label>Card Replacement</label> <p>P500</p></li>
            </ul>
        </div>
    </div>
</div>
<div class="bal-trans">
    <hr class="blue">
    <div class="row">
        <div class="col-lg-12"><p class="feature-title1">Eligibility</p></div>
    </div>
    <div class="row bRow">
        <div class="col-lg-3 text-center rRow">
            <img src="<?php echo $this->url->get('/assets/img/icons/man.png');?>" alt=""/>
            <p style="font-weight: bold;">Eligibility Criteria</p>
        </div>
        <div class="col-lg-9 lightgrey">
            <ul class="key-val">
                <li class="clearfix"><label>Income per month</label> <p>P30,000</p></li>
                <li class="clearfix"><label>Age</label> <p>21 years old</p></li>
                <li class="clearfix"><label>Employment</label> <p>Must be a reguar employee or if self employed, the business must be running for at least 2 years</p></li>
                <li class="clearfix"><label>Residence</label> <p>Home or Business address must be within 30km radius of a BPI or BPI Family Bank branches or Provincial Business Center</p></li>
                <li class="clearfix"><label>Legal Status</label> <p>Have a Tax Identification Number (TIN) and SSS/GSIS No.</p></li>
            </ul>
        </div>
    </div>
</div>

<div class="bal-trans">
    <hr class="blue">
    <div class="row">
        <div class="col-lg-8">
            <p class="feature-title1">Write a Review</p>
            <p>Do you have an american expres card. Write a review. you will be promted to login to facebook after submitting your review. We will not post to your wall without your permission.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <p class="lightgrey">Please rate this card.</p>
            <p class="lightgrey">Rating: (Poor) 
            <i class="fa fa-star gray"></i>
            <i class="fa fa-star gray"></i>
            <i class="fa fa-star gray"></i>
            <i class="fa fa-star gray"></i>
            <i class="fa fa-star gray"></i> (Excellent)</p>
            <textarea cols="" rows="5" placeholder="Write a review" style="width: 100%;"></textarea>
        </div>
        <div class="col-lg-4">
            <p>Tips for writing good</p>
            <ul>
                <li>What do you use this credit card for?</li>
                <li>What do you like/dislike about this card?</li>
                <li>Would you recommend this card to others?</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 clearfix">
            <img class="pull-right img-responsive" src="<?php echo $this->url->get('/assets/img/icons/facebook-button.png');?>" alt="">
        </div>
        <div class="col-lg-4">
            <p>Reviews and Ratings
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star gray"></i>
            
            Two Reviews
            </p>
            
        </div>
    </div>
</div>
<div class="bal-trans">
    <hr class="blue">
    <div class="row">
        <div class="col-lg-12"><p class="feature-title1">Reviews and Ratings</p></div>
    </div>
    <div class="row testimonial bRow">
        <div class="col-lg-3 text-center">
            <img src="<?php echo $this->url->get('/assets/img/testimonials/testi1.png');?>" alt="">
        </div>
        <div class="col-lg-9">
            <p>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star gray"></i>
            
            Good
            </p>
            <p>Bacon fatback corned beef turkey strip steak meatball. Landjaeger cow ground round beef strip steak pancetta. Pastrami corned beef tail frankfurter ham pork belly flank turducken spare ribs meatball fatback jerky swine short loin porchetta.Pig fatback corned beef strip steak bacon cow. Bacon fatback corned beef turkey strip steak meatball. Landjaeger cow ground.</p>
            <p class="testimony"><span>Brione Brion</span> on 1 June 2014</p>
        </div>
    </div>
    <div class="row testimonial">
        <div class="col-lg-3 text-center">
            <img src="<?php echo $this->url->get('/assets/img/testimonials/testi1.png');?>" alt="">
        </div>
        <div class="col-lg-9">
            <p>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star yellow"></i>
            <i class="fa fa-star gray"></i>
            
            Good
            </p>
            <p>Bacon fatback corned beef turkey strip steak meatball. Landjaeger cow ground round beef strip steak pancetta. Pastrami corned beef tail frankfurter ham pork belly flank turducken spare ribs meatball fatback jerky swine short loin porchetta.Pig fatback corned beef strip steak bacon cow. Bacon fatback corned beef turkey strip steak meatball. Landjaeger cow ground.</p>
            <p class="testimony"><span>Brione Brion</span> on 1 June 2014</p>
        </div>
    </div>
</div>
</div>