<div class="provider-page">
    <div class="row">
    	<div class="col-md-1 col-sm-1 col-xs-1">
            <img class="img-responsive" src="<?php echo $this->url->get('assets/img/pp-bpi-logo.png');?>" />
        </div>
        <div class="col-md-9 col-sm-9 col-xs-11 padding-0-5">
            <h1 class="result-title"><?php echo $title; ?></h1>
        </div>
        <div class="col-md-2 col-sm-2 hidden-xs back-text">
            <a href="<?php echo $this->url->get('result');?>"><?php echo $lang->_("provider_0"); ?></a>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12 provider-content">
            <p>As the oldest bank in the Philippines and in Southeast Asia, the Bank of the Philippine Islands (BPI) prides itself as one of the top three banks in the country and the financial group of the Ayala Group of Companies.</p>

    		<p>In 2000, BPI became the first bancassurance firm in the Philippines after its acquisition of five insurance companies under the Ayala Insurance Holdings Corporation, including FGU Insurance Corporation, Universal Reinsurance Corporation, Ayala Life Assurance, Inc., Ayala Health Care, Inc., and Ayala Plans, Inc.</p>

    		<p>BPI has garnered awards from Euromoney, Far Eastern Economic Review, The Banker, FinanceAsia, and Global Finance. The Bangko Sentral ng Pilipinas has also recognized BPI as the top commercial bank on OFW remittances from 2006 to 2008.</p>
        </div>
    </div>
    <hr class="blue-line"/>
    <div class="row">
        <div class="col-md-12">
            <h3>Credit Cards</h3>
            <p>There’s a BPI credit card for every lifestyle. BPI’s wide range of credit card products include specialty express credit card to earn miles, free travel insurance, and fuel rebates and rewards.</p>
        </div>
    </div>
    <div class="panel panel-default result-head" style="margin-bottom:0px;">
          <div class="panel-body">
              <div class="col-md-12 col-sm-12 col-xs-12 center-text">BPI Credit Cards</div>
          </div> 
    </div>
    <div class="cc-provider">
        <div class="row">
            <div class="col-md-2"><img class="img-responsive" src="<?php echo $this->url->get('assets/img/pp-bpi1.png');?>" /></div>
            <div class="col-md-9 padding-0-5"><h4>BPI SkyMiles MasterCard Classic and Platinum (The Pure Mileage Card)</h4></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="card-info">For aspiring and frequent global travelers, BPI formed a partnership with Delta Airlines to offer the BPI SkyMiles MasterCard Classic and Platinum. Cardholders automatically earn one (1) SkyMiles mile for every P45 spend anywhere using their card. These miles can be used to travel to over 900 cities, 160 countries at 6 continents through Delta Air Lines and its SkyMiles Airline partners.</p>
            </div>
        </div>
        <div class="row">              
            <div class="col-md-5 col-sm-5 col-xs-9">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 rRow">                                               
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12 card-details lightgrey">
                                <strong class="concat_char">This card is good for...</strong>
                                <ul class="list-unstyled">
                                    <li><i class="fa fa-check fa-lg"></i><span>Enjoy complimentary access to Club Manila lounge in NAIA 1</span></li>
                                    <li><i class="fa fa-check fa-lg"></i><span>Guaranteed financial protection in the event of untimely death or disability</span></li>
                                    <li><i class="fa fa-check fa-lg"></i><span>Avail of automobile insurance at installment using your card</span></li>
                                </ul>
                                <strong class="concat_char">But be aware that...</strong>
                                <ul class="list-unstyled">
                                    <li><i class="fa fa-minus fa-lg"></i><span>Account must remain active for points not to expire</span></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5 col-sm-5 hidden-xs">
                <div class="row marginb-10">
                    <div class="col-md-3 col-sm-3 center-text padding-0-5">
                        <strong>Cashback</strong>
                    </div>
                    <div class="col-md-3 col-sm-3 center-text padding-0-5">
                        <strong>Airmiles</strong>
                    </div>
                    <div class="col-md-3 col-sm-3 center-text padding-0-5">
                        <strong>Points</strong>
                    </div>
                    <div class="col-md-3 col-sm-3 center-text padding-0-5">
                        <strong>Annual Fee</strong>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 col-sm-3 rRow center-text padding-0-5">
                        <p>Up to <em>5.00%</em></p>
                        <p><a href="" class="more"><i class="fa fa-question-circle"></i> Show more</a></p>
                    </div>
                    <div class="col-md-3 col-sm-3 rRow center-text padding-0-5">
                        <p>1 mile =<br><em>$6</em></p>
                        <p><a href="" class="more"><i class="fa fa-question-circle"></i> Show more</a></p>
                    </div>
                    <div class="col-md-3 col-sm-3 rRow center-text padding-0-5">
                        <p>Up to<br><em>3x</em></p>
                        <p><a href="" class="more"><i class="fa fa-question-circle"></i> Show more</a></p>
                    </div>
                    <div class="col-md-3 col-sm-3 rRow center-text padding-0-5">
                        <p><em>$0</em>waived for first year*</p>
                        <p><a href="" class="more"><i class="fa fa-question-circle"></i> Show more</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-3">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 callus">
                        <button type="button" class="btn btn-warning btn-go" data-toggle="modal" data-target="#cc-modal">Go <i class=" hidden-xs fa fa-chevron-right"></i></button>

                        <span class="lightgrey" style="font-size: 12px;">or call us at</span>
                        <span class="call-num">0942-850-8823</span>
                        <span class="get-card"><a href=""><i class="fa fa-question-circle"></i> Will I get this card?</a></span>
                        <span class="compare lightgrey"><input type="checkbox">Compare in shortlist</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="cc-provider">
        <div class="row">
            <div class="col-md-2"><img class="img-responsive" src="<?php echo $this->url->get('assets/img/pp-bpi2.png');?>" /></div>
            <div class="col-md-9 padding-0-5"><h4>BPI Blue MasterCard (The Sensible Card)</h4></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="card-info">The BPI Express Credit Blue MasterCard is a start-up international credit card that offers the cardholder a free travel insurance worth P2 million. It is accepted in over 29 million establishments worldwide and allows the cardholder to make cash withdrawals of up to 30% of the credit limit in over 1 million Maestro/Cirrus ATMs worldwide.</p>
            </div>
        </div>
        <div class="row">              
            <div class="col-md-5 col-sm-5 col-xs-9">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 rRow">                                               
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12 card-details lightgrey">
                                <strong class="concat_char">This card is good for...</strong>
                                <ul class="list-unstyled">
                                    <li><i class="fa fa-check fa-lg"></i><span>Enjoy complimentary access to Club Manila lounge in NAIA 1</span></li>
                                    <li><i class="fa fa-check fa-lg"></i><span>Guaranteed financial protection in the event of untimely death or disability</span></li>
                                    <li><i class="fa fa-check fa-lg"></i><span>Avail of automobile insurance at installment using your card</span></li>
                                </ul>
                                <strong class="concat_char">But be aware that...</strong>
                                <ul class="list-unstyled">
                                    <li><i class="fa fa-minus fa-lg"></i><span>Account must remain active for points not to expire</span></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5 col-sm-5 hidden-xs">
                <div class="row marginb-10">
                    <div class="col-md-3 col-sm-3 center-text padding-0-5">
                        <strong>Cashback</strong>
                    </div>
                    <div class="col-md-3 col-sm-3 center-text padding-0-5">
                        <strong>Airmiles</strong>
                    </div>
                    <div class="col-md-3 col-sm-3 center-text padding-0-5">
                        <strong>Points</strong>
                    </div>
                    <div class="col-md-3 col-sm-3 center-text padding-0-5">
                        <strong>Annual Fee</strong>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 col-sm-3 rRow center-text padding-0-5">
                        <p>Up to <em>5.00%</em></p>
                        <p><a href="" class="more"><i class="fa fa-question-circle"></i> Show more</a></p>
                    </div>
                    <div class="col-md-3 col-sm-3 rRow center-text padding-0-5">
                        <p>1 mile =<br><em>$6</em></p>
                        <p><a href="" class="more"><i class="fa fa-question-circle"></i> Show more</a></p>
                    </div>
                    <div class="col-md-3 col-sm-3 rRow center-text padding-0-5">
                        <p>Up to<br><em>3x</em></p>
                        <p><a href="" class="more"><i class="fa fa-question-circle"></i> Show more</a></p>
                    </div>
                    <div class="col-md-3 col-sm-3 rRow center-text padding-0-5">
                        <p><em>$0</em>waived for first year*</p>
                        <p><a href="" class="more"><i class="fa fa-question-circle"></i> Show more</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-3">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 callus">
                        <button type="button" class="btn btn-warning btn-go" data-toggle="modal" data-target="#cc-modal">Go <i class=" hidden-xs fa fa-chevron-right"></i></button>

                        <span class="lightgrey" style="font-size: 12px;">or call us at</span>
                        <span class="call-num">0942-850-8823</span>
                        <span class="get-card"><a href=""><i class="fa fa-question-circle"></i> Will I get this card?</a></span>
                        <span class="compare lightgrey"><input type="checkbox">Compare in shortlist</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr class="blue-line"/>
</div>	
<!--
continue here
-->