<?php 
$url = $this->config->project->cms_url . 'widgets/newsletter';
$cms = json_decode(file_get_contents($url));
$cms = $cms->data;
?>
<div class="side-newsletter-container well hidden-xs">
	<div class="panel panel-default result-head">
      <div class="panel-body">
        <?php echo $cms->header; ?>
      </div>
    </div>
    <div>
    	<p><?php echo $cms->caption; ?></p>
  	</div>
  	<div>
    	<img src="<?php echo $cms->image->path; ?>" />
  	</div>
  	<div class="left-text">
    	<ul class="list-unstyled">
		  <li><p class="glyphicon glyphicon-ok"></p> <?php echo $cms->text_1; ?></li>
		  <li><p class="glyphicon glyphicon-ok"></p> <?php echo $cms->text_2; ?></li>
		  <li><p class="glyphicon glyphicon-ok"></p> <?php echo $cms->text_3; ?></li>
		</ul>
  	</div>
  	<div class="newsletter-box">
	  <p style="font-size: 16px;"><?php echo $cms->subscriber_counter; ?></p>
	  <div class="form-group">
	    <input type="text" class="form-control" id="email" placeholder="<?php echo $cms->email_placeholder; ?>">
	  </div>
	  <div class="form-group">
		<button type="button" class="btn btn-warning btn-find"><?php echo $cms->button_warning; ?> <i class="fa fa-chevron-right"></i></button>
	  </div>
	  <p class="notification-text"><?php echo $cms->privacy_promises; ?></p>
  	</div>
</div>