<!DOCTYPE html>
<html lang="en">
	<head>
		<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />	
		<title>Contact Us</title>
	</head>
	<body marginheight="0" topmargin="0" marginwidth="0" leftmargin="0" background="" style="margin: 0px; background-color: #ffffff;" bgcolor="#ffffff">
		<h3>Contact Us Information:</h3>
		<?php foreach ($content as $key => $value) {  echo '<p><strong>'.$key.'</strong>:'.$value.'</p>'; } ?>
	</body>
</html>