<?php $this->tag->setDoctype(\Phalcon\Tag::HTML5); echo $this->tag->getDoctype(); ?>
<html xmlns:fb="http://ogp.me/ns/fb#" xmlns:og="http://ogp.me/ns#" lang="en">
    <head>
        <?php echo $this->tag->getTitle(); ?>

        <link rel="canonical" href="<?php echo $this->url->get(ltrim($this->request->getURI(), '/')); ?>"/>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="Cache-control" content="public">
        <meta property="og:type" content="website"/>

        <meta property="og:image" content="<?php echo 'http:'.$this->url->get('assets/img/'.$meta['image']); ?>"/>
        <meta property="og:title" content="<?php echo isset($title) ? $title : ''; ?>" />
        <meta property="og:url" content="<?php echo $this->url->get(ltrim($this->request->getURI(), '/')); ?>"/>

        <meta property="og:site_name" content="<?php echo $this->config->project->name; ?>"/>
        <meta property="og:description" content="<?php echo $meta['description']; ?>"/>

        <meta name='keywords' content="<?php echo $meta['keywords']; ?>"/>
        <meta name="description" content="<?php echo $meta['description']; ?>"/>


        <!-- HTML5 shim for IE backwards compatibility -->
        <!--[if lt IE 9]>
        <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <?php if(isset($this->config->project->social->google)): ?>
            <link href="https://plus.google.com/<?php echo $this->config->project->social->google; ?>" rel='publisher' />
        <?php endif; ?>
        <link href="<?php echo $this->url->get('assets/img/favicon.ico'); ?>" rel="shortcut icon" type="image/vnd.microsoft.icon" />
        <?php $this->assets->outputCss('outsideCss'); ?>
        <?php $this->assets->outputCss('commonCss'); ?>
        <?php $this->assets->outputCss('pageCss'); ?>
    </head>
  <body>
   <header>
        <div class="header">
            <?php echo $this->widget->getheader($widget_list); ?>
        </div>

        <div class="menu">
            <?php echo $this->widget->getmenu($widget_list); ?>
        </div>   
   </header>

   <content>
        <div class="placeholder">
            <?php echo $this->widget->getplaceholder($widget_list); ?>
        </div>
        <section class="container sec_grp">
            <?php if( $this->widget->getsidebar($widget_list) ) { ?><div class="row"><div class="sidebar"><?php echo $this->widget->getsidebar($widget_list); ?></div><?php } ?>
            
                <div class="content">
                    <?php echo $this->getContent(); ?>
                </div>

            <?php if( $this->widget->getsidebar($widget_list) ) { ?></div><?php } ?>
        </section>
   </content>

   <footer>
        <div class="newsletter">
            <?php echo $this->widget->getnewsletter($widget_list); ?>
        </div>

        <div class="seotext">
            <?php echo $this->widget->getseotext($widget_list); ?>
        </div>

        <div class="subfooter">
            <?php echo $this->widget->getsubfooter($widget_list); ?>
        </div>

        <div class="footer">
            <?php echo $this->widget->getfooter($widget_list); ?>
        </div>
   </footer>
    <div id="fb-root"></div>
    <?php $this->assets->outputJs('outsideJs'); ?>
    <?php $this->assets->outputJs('commonJs'); ?>
    <?php $this->assets->outputJs('pageJs'); ?>
    <script type="text/javascript">
        <?php if(isset($this->config->project->analytics->piwik->enabled)): ?>
        //Piwik
        var _paq = _paq || [];
            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            (function() {
            var u=(("https:" == document.location.protocol) ? "https" : "http") + "://analytics.compargo.com/";
            _paq.push(['setTrackerUrl', u+'piwik.php']);
            _paq.push(['setSiteId', <?php echo $this->config->project->analytics->piwik->idsite; ?>]);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript';
            g.defer=true; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
        //end Piwik Code
        <?php endif; ?>

        <?php if(isset($this->config->project->analytics->google->apiKey)): ?>
        //g analytics
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', "<?php echo $this->config->project->analytics->google->apiKey; ?>"]);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
        //end g analytics
        <?php endif; ?>
            
        <?php if(isset($this->config->project->social->google)): ?>
        //g+
        window.___gcfg = {lang: "<?php echo $this->registry->language->code; ?>"};
        (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/platform.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
        //end g+
        <?php endif; ?>
        
        <?php if(isset($this->config->project->appID->facebook)): ?>
        //fb
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/<?php echo $this->registry->language->code; ?>/sdk.js#xfbml=1&appId=<?php echo $this->config->project->appID->facebook; ?>&version=v2.0";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        //end fb
        <?php endif; ?>
        
        <?php if(isset($this->config->project->social->twitter)): ?>
        //twitter
        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.type = 'text/javascript';
            js.async = true;
            js.src = "https://platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'twitter-wjs'));
        //end twitter
        <?php endif; ?>
    </script>

    <?php if(isset($this->config->project->analytics->piwik->enabled)): ?>
        <noscript><p><img src="<?php echo $this->config->project->analytics->piwik->url; ?>?idsite=<?php echo $this->config->project->analytics->piwik->idsite; ?>" style="border:0;" alt="" /></p></noscript>
    <?php endif; ?>

    <?php echo $this->widget->getmodal($widget_list); ?>
    </body>
</html>